# server port
server:
  port: 0

# logging
logging:
  level:
    com.ssafy.analysisservice: debug

# MSA setting
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}

# spring setting
spring:
  application:
    name: analysis-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, metrics, prometheus, busrefresh
