# server port
server:
  port: 0

---
# logging
logging:
  level:
    org.hibernate: debug
    com.ssafy.userservice: debug

# MSA setting
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}

# spring setting
spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    port: 6379
  # h2 setting
  h2:
    console:
      enabled: true
  # jpa setting
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    open-in-view: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, metrics, prometheus, busrefresh
